#!/usr/bin/env bash
#display information about subdomains.

information () {
	get=$(dig "$1" | grep -A1 "ANSWER SECTION:" | tail -n 1)
}

options="www lb-01 web-01 web-02"

if [ "$#" -eq 1 ]; then
	for subdomain in $options; do
		information "$subdomain.$1"
		echo "$get $subdomain" | awk '{ print "The subdomain " $6 " is a " $4 " record and points to " $5 }'
	done
else
	information "$2.$1"
	echo "$get $2" | awk '{ print "The subdomain " $6 " is a " $4 " record and points to " $5 }'
fi
