#!/usr/bin/env bash
# print numbers from 1 to 100.

for ((c = 1; c <= 100; c++));
do
    if ((c % 3 == 0 && c % 5 == 0)); then
	echo "FizzBuzz"
    elif ((c % 5 == 0)); then
	echo "Buzz"
    elif ((c % 3 == 0)); then
	echo "Fizz"
    else
	echo "$c"
    fi
done


