#!/usr/bin/env bash
# print holberton 10 times

counter=0
while ((counter < 10));
do
	if [ $counter = 3 ]; then
		echo "bad luck"
	elif [ $counter = 7 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
    	((counter++))
done
