#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:

hour=0
while [ $hour != 13 ];
do
    min=1
    echo "Hour: $hour"
    while [ $min != 60 ];
    do
	echo $min
	((min++))
    done
    ((hour++))
done
