#!/usr/bin/env bash
#run nginx from another user
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
